# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Liam/Documents/GitHub/Cordic/Cordic.srcs/sources_1/ip/TRIG_LUT/TRIG_LUT.xci
# IP: The module: 'TRIG_LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Liam/Documents/GitHub/Cordic/Cordic.srcs/sources_1/ip/TRIG_LUT/TRIG_LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TRIG_LUT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Liam/Documents/GitHub/Cordic/Cordic.srcs/sources_1/ip/TRIG_LUT/TRIG_LUT.xci
# IP: The module: 'TRIG_LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Liam/Documents/GitHub/Cordic/Cordic.srcs/sources_1/ip/TRIG_LUT/TRIG_LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TRIG_LUT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
